# Workflow name shown in the GitHub Actions
name: 'Build and Push to GHCR'

# Trigger the workflow when pushing a tag like: v1.0.0
on:
  release:
    types: [ published ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Set up checkout
        uses: actions/checkout@v4

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GHCR_TOKEN }}